abdominal_pain(diarrhea).
blisters_on_rash(chickenpox).
chest_tightness(asthma).
cloudy_or_bloody_urine(uti).
contact_with_chickenpox(chickenpox).
contact_with_diarrhea_case(diarrhea).
cough(bronchitis).
cough(cold).
cough(influenza).
cough(pneumonia).
dark_skin_patches(diabetes).
ear_drainage(ear_infection).
ear_pain(ear_infection).
family_history_of_diabetes(diabetes).
fever(chickenpox).
fever(cold).
fever(diarrhea).
fever(ear_infection).
fever(influenza).
fever(pneumonia).
frequent_urination(uti).
hunger(diabetes).
instruction_difficulty(alzheimers).
itchy_rash(chickenpox).
loose_stools(diarrhea).
memory_changes(alzheimers).
mucus_production(bronchitis).
mucus_production(pneumonia).
muscle_aches(influenza).
nausea_or_vomiting(diarrhea).
painful_urination(uti).
personality_changes(alzheimers).
rash(chickenpox).
runny_nose(cold).
shortness_of_breath(asthma).
slow_healing_sores(diabetes).
sore_throat(cold).
thirst(diabetes).
unusual_food_or_drink_consumption(diarrhea).
urination(diabetes).
unexplained_weight_loss(diabetes).
wheezing(asthma).
wheezing(bronchitis).
word_finding_difficulty(alzheimers).